# Generated by Django 4.2.6 on 2024-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_rename_products_product_alter_pickups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickups',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
