# Generated by Django 4.2.6 on 2024-03-02 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_pickups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickups',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
