# Generated by Django 4.2.6 on 2024-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0005_picker_pickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picker_pickups',
            name='pickups',
            field=models.ManyToManyField(blank=True, to='pickup.pickups'),
        ),
    ]
