# Generated by Django 4.2.6 on 2024-03-02 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_picker_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
