# Generated by Django 4.2.6 on 2024-03-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notifications_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(),
        ),
    ]
